modLoader="javafml"
loaderVersion="[2,)"
license="Apache 2.0"
issueTrackerURL="https://github.com/Luligabi1/FuelInfo/issues"
[[mods]] 
   modId="fuelinfo"
   version="${version}"
   displayName="FuelInfo"
   displayURL="https://www.curseforge.com/minecraft/mc-mods/fuel-info"
   logoFile="icon.png"
   authors="Luligabi1"
   credits="With translations by EvanHsieh0415, Rad233, JonnyBro and Calvineries."
   description="Extra info on your fuels whenever you're smelting stuff."
[[mixins]]
   config="fuelinfo-common.mixins.json"
[[dependencies.fuelinfo]]
   modId="neoforge"
   type="required"
   versionRange="[20.4,)"
   ordering="NONE"
   side="CLIENT"
[[dependencies.fuelinfo]]
   modId="minecraft"
   type="required"
   versionRange="[1.20.4,1.21)"
   ordering="NONE"
   side="CLIENT"