org.gradle.jvmargs=-Xmx2048M

minecraft_version=1.21.10
# Mod
archives_base_name=FuelInfo
mod_version=2.1+1.21.10
maven_group=me.luligabi
discordAnnouncementIconURL=https://cdn.modrinth.com/data/J1ueTDcI/icon.png
# Common
architectury_version=18.0.5
yacl_version=3.8.0+1.21.9
# Fabric
fabric_loader_version=0.17.3
fabric_api_version=0.136.0+1.21.10
modmenu_version=16.0.0-rc.1
# NeoForge
neoforge_version=21.10.29-beta