# Important Notes:
# Every field you add must be added to buildSrc/src/main/groovy/multiloader-common.gradle expandProps map.

# Project
version=3.0.0+26.2
group=me.luligabi.fuelinfo
java_version=25

# Common
minecraft_version=26.2
mod_name=FuelInfo
mod_author=Luligabi1
mod_id=fuelinfo
license=Apache-2.0
credits=With translations by EvanHsieh0415, Rad233, JonnyBro and Calvineries.
description=Displays extended info on vanilla Furnaces (including its variants) and Brewing Stands, such as how many items can be smelted, time remaining and how many (sets of) potions can be brewed.
minecraft_version_range=[26.2, 27.0)
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=26.2-1
yacl_version=3.9.4+26.2

# Fabric, see https://fabricmc.net/develop/ for new versions
fabric_version=0.153.0+26.2
fabric_loader_version=0.19.3
modmenu_version=20.0.0-beta.4

# NeoForge, see https://projects.neoforged.net/neoforged/neoforge for new versions
neoforge_version=26.2.0.7-beta
neoforge_loader_version_range=[4,)

# Discord Announcement
discordAnnouncementIconURL=https://cdn.modrinth.com/data/J1ueTDcI/icon.png

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
